{% set name = "chemiscope" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/chemiscope-{{ version }}.tar.gz
  sha256: 5579cafc2872940c01481fa9a27a4c82622a606226b158790c4499e68bca6de9

build:
  entry_points:
    - chemiscope-input = chemiscope.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - jupyterlab >=4.0
    - pip
  run:
    - python >={{ python_min }}
    - ase
    - numpy
    - ipywidgets >=7,<9

test:
  imports:
    - chemiscope
  commands:
    - pip check
    - chemiscope-input --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Helpers to work with the chemiscope interactive structure/property explorer for materials and molecules
  home: https://github.com/lab-cosmo/chemiscope
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
